# Generated by Django 4.2.2 on 2023-06-14 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0002_author_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 6, 38, 39, 963485, tzinfo=datetime.timezone.utc)),
        ),
    ]
