# Generated by Django 4.2.2 on 2023-06-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
